name: "My-Test-Workflow"
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print README
        run: cat README.md